# permissions for end users to edit sidecarbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sidecarb-editor-role
rules:
- apiGroups:
  - darkowlzz.space
  resources:
  - sidecarbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - darkowlzz.space
  resources:
  - sidecarbs/status
  verbs:
  - get
