# permissions for end users to view sidecarbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sidecarb-viewer-role
rules:
- apiGroups:
  - darkowlzz.space
  resources:
  - sidecarbs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - darkowlzz.space
  resources:
  - sidecarbs/status
  verbs:
  - get
