# permissions for end users to view sidecaras.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sidecara-viewer-role
rules:
- apiGroups:
  - darkowlzz.space
  resources:
  - sidecaras
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - darkowlzz.space
  resources:
  - sidecaras/status
  verbs:
  - get
